install.packages("recommenderlab")
library(recommenderlab)
data("MovieLense")
movie_data <- MovieLense

# Ensure that movie_data is a "realRatingMatrix" object
movie_data <- as(movie_data, "realRatingMatrix")

# Split the data into training and test sets (80/20 split)
set.seed(123) # Set seed for reproducibility
splits <- evaluationScheme(data = movie_data, method = "split", train = 0.8, k = 1, given = -1)
train_data <- getData(splits, type = "train")
test_data <- getData(splits, "unknown")

# Building the model
recommendation_model <- Recommender(data = train_data, method = "UBCF")
model <- recommendation_model

# Make predictions on the test data
predicted_ratings <- predict(model, test_data, type = "ratings")

true_ratings <- as.vector(test_data@data)
predicted_ratings_vector <- as.vector(predicted_ratings@data)
rmse <- sqrt(mean((true_ratings - predicted_ratings_vector)^2, na.rm = TRUE))
print(paste("RMSE:", rmse))




# Getting recommendations for all users in the test set
recommendations <- predict(model, test_data, type = "topNList", n = 10)

# Converting recommendations to a list
recommendation_list <- as(recommendations, "list")

# Flattening the list to get movie IDs
movie_ids <- unlist(recommendation_list)

# Counting the occurrence of each movie
movie_counts <- table(movie_ids)

# Sorting movies by the frequency of recommendation
most_recommended_movies <- sort(movie_counts, decreasing = TRUE)

# Printing the most recommended movies
print(most_recommended_movies)


# Convert the recommendations object to a list
recommendation_list <- as(recommendations, "list")

# Access recommendations for a specific user (e.g., the first user)
user_recommendations <- recommendation_list[[1]]

# Print the recommendations for the user
print(user_recommendations)



recommendation_model <- Recommender(data = movie_data, method = "UBCF")
user_recommendations <- predict(object = recommendation_model, newdata = movie_data[1,])
user_recommendations
as(user_recommendations, "list")



get_recommendations <- function(user_id, model, data) {
  print(paste("Getting recommendations for User", user_id))
  
  if (user_id %in% rownames(data)) {
    print("User found in the data.")
    user_data <- data[user_id, ]
    recommendations <- predict(model, user_data)
    
    if (length(recommendations) > 0) {
      print("Recommendations generated.")
      return(as(recommendations, "list"))
    } else {
      print("No recommendations generated by the model.")
      return(get_popular_items(data))
    }
    
  } else {
    print("User not found in the data. Returning popular items.")
    return(get_popular_items(data))
  }
}

user_recommendations <- get_recommendations("2", recommendation_model, movie_data)
print(user_recommendations)



